version: '3.8'

services:
  db:
    container_name: mysql_db
    image: mysql:8.4
    env_file:
      - ./sql_scripts/.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql_scripts/config-file.cnf:/etc/mysql/conf.d/config-file.cnf
      - ./sql_scripts/1_tables.sql:/docker-entrypoint-initdb.d/1_tables.sql
      - ./sql_scripts/2_connection.sql:/docker-entrypoint-initdb.d/2_connection.sql
      - ./sql_scripts/3_admins.sql:/docker-entrypoint-initdb.d/3_admins.sql
      - ./sql_scripts/4_amenities.sql:/docker-entrypoint-initdb.d/4_amenities.sql
      - ./sql_scripts/5_countries.sql:/docker-entrypoint-initdb.d/5_countries.sql

  nginx:
    container_name: nginx_proxy
    restart: always
    image: nginx:1-alpine
    ports:
      - 80:80
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  web:
    container_name: web_app
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db


volumes:
  db_data:
