version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hbnb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  web:
    build: .
    container_name: web_app
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  db_data:
