version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hbnb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - 80:80
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  web:
    build: .
    container_name: web_app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=dh72h3f98dj18z2377a2d9h82f91fdd9d8kwq9990sidqjwdjoj2fhsl241
      - DATABASE_TYPE=mysql
      - DATABASE_URL=mysql+mysqlconnector://root:root@0.0.0.0/hbnb
    depends_on:
      - db


volumes:
  db_data:
