INSERT IGNORE INTO amenities (name)
VALUES
('Pool'),
('Bathtub'),
('Cleaning products'),
('Shampoo'),
('Conditioner'),
('Body soap'),
('Bidet'),
('Outdoor shower'),
('Hot water'),
('Essentials'),
('Hangers'),
('Bed linens'),
('Extra pillows and blankets'),
('Room-darkening shades'),
('Iron'),
('Safe'),
('Mosquito net'),
('Clothing storage'),
('TV'),
('Air conditioning'),
('Indoor fireplace'),
('Heating'),
('Fire extinguisher'),
('First aid kit'),
('Wifi'),
('Kitchen'),
('Refrigerator'),
('Cooking basics'),
('Dishes and silverware'),
('Freezer'),
('Stove'),
('Oven'),
('Hot water kettle'),
('Coffee maker'),
('Wine glasses'),
('Toaster'),
('Baking sheet'),
('Barbecue utensils'),
('Dining table'),
('Coffee'),
('Waterfront'),
('Private beach access'),
('Lake access'),
('Private entrance'),
('Patio or balcony'),
('Private backyard'),
('Outdoor furniture'),
('Outdoor dining area'),
('BBQ grill'),
('Boat slip'),
('Private hot tub'),
('Long term stays allowed'),
('Self check-in'),
('Building staff'),
('Washer'),
('Dryer'),
('Smoke alarm'),
('Carbon monoxide alarm'),
('Courtyard view'),
('Garden view'),
('Paid washer'),
('Room-darkening shades'),
('Drying rack for clothing'),
('Books and reading material'),
("Children's books and toys"),
('Board games'),
('Babysitter recommendations'),
('Lock on bedroom door'),
('Patio or balcony'),
('Backyard'),
('Fire pit'),
('Hammock'),
('Shared outdoor kitchen'),
('Bikes'),
('Kayak'),
('Free street parking'),
('Single level home'),
('Pets allowed'),
('Luggage dropoff allowed'),
('Smoking allowed'),
('Host greets you'),
('Mountain view'),
('Hot tub'),
('Exterior security cameras on property'),
('Free parking'),
('Hair dryer'),
('Lake view'),
('HDTV with Netflix, standard cable'),
('Mini fridge'),
('Induction stove'),
('Stainless steel oven'),
('Laundromat nearby'),
('Free carport'),
('Shared gym nearby'),
('Breakfast'),
('Cleaning available during stay'),
('Microwave'),
('Blender'),
('Private patio or balcony'),
('Shower gel'),
('Record player'),
('Bluetooth sound system'),
('Portable heater'),
('Gas stove'),
('Smart lock'),
('Sound system'),
('Fireplace guards'),
('Window guards'),
('Portable fans'),
('Rice maker'),
('Resort access'),
('Outdoor kitchen'),
('Lockbox'),
('Exercise equipment'),
('Ceiling fan'),
('Electric stove'),
('Free resort access'),
('Sun loungers'),
('City skyline view'),
('Valley view'),
('Pool view'),
('Free washer'),
('Free dryer'),
('Ethernet connection'),
('Pool table'),
('Mini golf'),
('Crib'),
('Outdoor playground'),
('Window AC unit'),
('Paid parking off premises'),
('EV charger'),
('King bed'),
('Instant Book'),
('Dedicated workspace');
