template:
  swagger: '2.0'
  info:
    title: HBNB API
    description: API for Holberton AirBNB project
    contact:
      responsibleDeveloper:
        - Wilson Antognazza
        - Matias Davezac
        - Alison Alvez
      email:
        - manuelantognazza@gmail.com
        - matiasdavezac@gmail.com
        - alisonalvez05@gmail.com
    version: '0.1.0'
  basePath: /
  schemes:
    - http